language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- pip install -e .
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  password:
    secure: ip6CuQlwWepxU1nWV/Dcz8LFeHJmA5QaLtfFB9kdOxE0KbA0vGaDRJTKVkJX5TURSUI+KvfR8+alceqy75F9ni/ABLmOeqwcsX88wRcxA1y7OlknV/mOwlXC7p8isIlxPjXtiwxa0yjLgPcxvz6oKH/ZJ3sMNo440kn6OhfZY7x1q7wWCSaXgDQ9za9zvdhTao93SmcJwl9CnkqNNwY2HnyMsYtLHKmlQekuAUA/0mvAIuPp732U92muAmotbGu+guUCRcf5UB8Zex9JpJofC9NpFxhuAj2z2zhjSQtQswQQe8/m0hERP496D0i7MamOF3C6qGXeoj+dN9pisH4VUc1TiZpBAY4oSPFG/rZw72lzt1e3D1EqRkHKqkGBQfAtQM5LFgSqabWne2l4ciUdsUwSc3ILDG7iXa/mYcV5omdQV5iE/ietGrtaxmefmtQCvY/YQ1fgpKybtJo17XUyYjcNaAhmGv19PkIMDsw7aLNenpftQWPWXn2aSvZjmPvrbpB/M1IQqEQ9hSKujmc41W/0Vkf0XpOKJUsCt2+9u0XkhzS8W3OoFGSquwiPH07T7Zp/yt1KrUbv7CYPHy9TAoPAuIBGqdrsU/O4AsgaNNN4I7le1+/voxZBeSlH1UdKTxZZ2DsgT8MEqPgJUM6nyHvh4vwmSM0GUZTI6l1Wxgw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: opennode/nodeconductor-paas-oracle
